### ISSUE TITLE
ARM image

### ISSUE THREAD

**Issue by francescor** [silinternational/restic-backup-restore#10]
Hi there!
Thanks for your work!

I would like to request a release of the image for the ARM64 architecture. Currently, only the x86_64 version is available, and having an ARM64 option would be incredibly helpful for us to we can move to cheaper ARM-based systems.

Thank you for considering this!

**Comment by briskt** [comment]
Hi, @francescor! Thanks for the suggestion. I pushed an [image](https://hub.docker.com/layers/silintl/restic-backup-restore/develop/images/sha256-4fedd16b7758b878176acc7c87614632e9aa1b6bc75f86e6a1c5b13d80c70b49?context=explore) with arm64 variant on the `develop` tag. Can you let me know if that works for you?

**Comment by briskt** [comment]
Resolved by #11
